### ISSUE TITLE
Duplicate amp component JS in full html

### ISSUE THREAD

**Issue by RainbowArray** [Lullabot/amp-library#29]
In Drupal 7, I'm seeing an error where the script tags for component JS are being added a second time when full HTML processing is turned on. I'm not seeing this error in Drupal 8. Examples include amp-iframe, amp-twitter, and amp-analytics. In Drupal 7, the tags are initially added to $head which appears towards the top of the head element. In Drupal 8, the tags are output by the JS placeholder, which is just above the main amp script tag. Maybe that has something to do with it? In any case, when full HTML processing is turned off, this doesn't happen, so it's something to do with the AMP library. I don't see any code in the D7 module that is doing this in conjunction with the full HTML pass, so I can only assume it's the library itself.

**Comment by sidkshatriya** [comment]
@mdrummond I looked at this. It turns out this is a problem with the D7 amp module. The D7 module behavior is different from the D8 module behavior. 

While D8 outputs `<script>` tags as `<script src="..." async></script>` (which is correct)
D7 outputs `<script src="..." async=async></script>`

The wrong async attribute value  causes the validator to think the amp-iframe script tag is incorrect and it includes it again in the head. It should be `async=""` (https://github.com/ampproject/amphtml/blob/master/validator/validator.protoascii#L2974 )

This has been fixed in:
http://drupalcode.org/project/amp.git/commit/362d848

Closing ticket. Please re-open if this does not solve your problem.
